# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20170214_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name_of_activity',
            new_name='activity_name',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='position_of_activity',
            new_name='activity_position',
        ),
    ]
