# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20170214_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='activity day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='activity time'),
            preserve_default=False,
        ),
    ]
