# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20170214_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_code',
        ),
    ]
